services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
  validate:
    build: .
    environment:
      - KEYS=Symmetric256:403697de87af64611c1d32a05dab0fe1fcb715a86ab435f1ec99192d79569388
      - ISSUER=compose
      - REDIS_URL=redis://redis:6379
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - validate
    restart: unless-stopped

volumes:
  redis_data: